name: "CI/CD"

on:
    pull_request:
        branches:
            - '**'
    push:
        branches:
            - '**'

jobs:
    build:
        name: Build & Release
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        steps:
            #1 Checkout Repository
            - name: Checkout Repository
              uses: actions/checkout@v4

            #2 Setup Java
            - name: Set Up Java
              uses: actions/setup-java@v4
              with:
                distribution: 'oracle'
                java-version: '21'

            #3 Setup Flutter
            - name: Set Up Flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: 3.24.1
            - run: flutter --version
